### ISSUE TITLE
Javascript error in the dash portal of Grid2Viz

### ISSUE THREAD

**Issue by AvisP** [rte-france/grid2viz#107]
I am getting these numerous error messages of Javascript when I opened the 'Scenario Overview' tab. Details of the error. Screenshot provided below

```
ReferenceError: A nonexistent object was used in an `State` of a Dash callback. The id of this object is `cards_container` and the property is `children`. The string ids in the current layout are: [scenario, agent_ref, agent_study, user_timestep_store, user_timestamps_store, window, page, relayoutStoreMicro, reset_timeseries_table_macro, scen_lbl, select_ref_agent, select_study_agent, user_timestamp_div, badge_ts, enlarge_left, user_timestamps, enlarge_right, nav_scen_select, nav_scen_over, nav_agent_over, nav_agent_study, nav_simulation, page_help, nav_help, loading-episode-button, loading-2, loading-output-2, loading-stepper-episode, url, page-content, loading_modal]

    at refErr (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:516:9)

    at fillVals (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:504:5)

    at _callee$ (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:934:53)

    at tryCatch (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:409:2404)

    at Generator._invoke (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:409:1964)

    at Generator.next (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:409:3255)

    at asyncGeneratorStep (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:413:103)

    at _next (http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:414:194)

    at http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_0m1670028437.dev.js:414:364

    at new Promise (<anonymous>)
```
![Screen Shot 2022-12-05 at 2 05 16 PM](https://user-images.githubusercontent.com/10809866/205722253-81974736-615b-4d0f-bb32-3d637d562b79.png)

**Comment by marota** [comment]
It is difficult to know what's happening juste based on that.
try to provide a reproducible description of the environment you have been using and what you've been trying. You can for instance provide an example of the agent episodes you have been trying to load, and from which environment they were generated (grid2op version, env name)

**Comment by AvisP** [comment]
Hi Marota,

I have put the log files and the grid2viz notebook over [here](https://easyupload.io/links?id=https://easyupload.io/ylhulc).

Basically I created these using the PPO_RLLIB algorithm on the l2rpn_case14_sandbox environment with latest version of grid2ops (1.8.1). I am providing the training and evaluation script I used.

**Training:**
```
import grid2op
from grid2op.gym_compat import GymEnv, BoxGymObsSpace, BoxGymActSpace
from grid2op.Backend import PandaPowerBackend
from lightsim2grid import LightSimBackend
from l2rpn_baselines.PPO_RLLIB import PPO_RLLIB, train
from l2rpn_baselines.PPO_RLLIB.rllibagent import RLLIBAgent
from grid2op.Reward import LinesCapacityReward  # or any other rewards
from grid2op.Chronics import MultifolderWithCache  # highly recommended
import copy
import re
import ray

env_name = "l2rpn_case14_sandbox"  # or any other name
obs_attr_to_keep = ["day_of_week", "hour_of_day", "minute_of_hour", "prod_p", "prod_v", "load_p", "load_q",
                    "actual_dispatch", "target_dispatch", "topo_vect", "time_before_cooldown_line",
                    "time_before_cooldown_sub", "rho", "timestep_overflow", "line_status",
                    "storage_power", "storage_charge"]
act_attr_to_keep = ["redispatch"]

env = grid2op.make(env_name, backend=LightSimBackend())

ray.init()

train(env,
        iterations=10,  # any number of iterations you want
        save_path="./saved_model/PPO_RLLIB",  # where the NN weights will be saved
        name="test",  # name of the baseline
        net_arch=[100, 100, 100],  # architecture of the NN
        save_every_xxx_steps=2,  # save the NN every 2 training steps
        env_kwargs={"reward_class": LinesCapacityReward,
                    "chronics_class": MultifolderWithCache,  # highly recommended
                    "data_feeding_kwargs": {
                        'filter_func': lambda x: re.match(".*00$", x) is not None  #use one over 100 chronics to train (for speed)
                        }
        },
        obs_attr_to_keep=copy.deepcopy(obs_attr_to_keep),
        act_attr_to_keep=copy.deepcopy(act_attr_to_keep),
        verbose=True)

env.close()
ray.shutdown()
```

**Evaluation**

```
import grid2op
from grid2op.Reward import LinesCapacityReward  # or any other rewards
from lightsim2grid import LightSimBackend  # highly recommended !
from l2rpn_baselines.PPO_RLLIB import evaluate

nb_episode = 7
nb_process = 1
verbose = True
env_name = "l2rpn_case14_sandbox"
env = grid2op.make(env_name,
                reward_class=LinesCapacityReward,
                backend=LightSimBackend()
                )
try:
    evaluate(env,
            nb_episode=nb_episode,
            load_path="./saved_model/PPO_RLLIB",  # should be the same as what has been called in the train function !
            name="test",  # should be the same as what has been called in the train function !
            logs_path = "./logs/PPO_RLLIB/",
            nb_process=1,
            verbose=verbose,
            )
finally:
    env.close()
```
Hope that helps to reproduce the error!

**Comment by marota** [comment]
Hi,
Could you provide these logs using Grid2op 1.6.4
This was the latest Grid2op version validated on the master branch

**Comment by AvisP** [comment]
Hi marota, 

I see that the master branch of gridops has been updated to 1.8.1. https://github.com/rte-france/Grid2Op/tree/master

Is it not possible to test on this one? as there were some other issues happening related to grid2ops which is why I had to upgrade to 1.8.1

Thanks

**Comment by marota** [comment]
Hi,
Actually it runs just fine on my side (on ubuntu 20.04)
![image](https://user-images.githubusercontent.com/5496312/214891224-09eeb2df-ae07-4bda-9520-bd3a0d922963.png)

![image](https://user-images.githubusercontent.com/5496312/214891514-d92ee6bc-8f72-4e66-a5ce-428b4b5b8410.png)

I created the "grid2viz cache data" as is
``
grid2viz --agents_pathTo/Grid2Viz_PPO --cache --n_cores 5
``
But I first removed from the Grid2Viz_PPO folder things that were not agent logs (notebook and "__MAXOSX" folder)
You should see a "_cache" folder created by Grid2viz

then I was able to watch your agent in Grid2viz with
``
grid2viz --agents_pathTo/Grid2Viz_PPO 
``
So maybe try to follow this procedure if you have not done it this way.
Otherwise it is hard to tell from my side what's going on, something probably related to the OS

**Comment by AvisP** [comment]
so when I am running this command 

`grid2viz --agents_path /........./Grid2Viz_PPO/PPO_RLLIB --cache --n_cores 1` I get the following output 

```
Using default environment at /................/venvs/L2PRN/lib/python3.10/site-packages/grid2viz/data/rte_case14_realistic
The config file used is located at: /............../venvs/L2PRN/lib/python3.10/site-packages/grid2viz/config.ini
Agents data used is located at: /................../logs/PPO_RLLIB2
Starting Multiprocessing for reading the best agent of each scenario
Multiprocessing done
```

But don't see the `_cahce` folder created. I checked by turning on hidden folder visible also.... what might I be doing wrong here?

Also I noticed doing a pip install of grid2viz install grid2ops 1.6.4 instead of the latest one

**Comment by marota** [comment]
what about running 
``
grid2viz --agents_path **/........./Grid2Viz_PPO** --cache --n_cores 1
``

**Comment by AvisP** [comment]
That worked! I had to set the path to one level higher in the directory, thanks!

I noticed some warnings though like the following when running the commands on [these](https://easyupload.io/kh1e34) logs 

```
Environment
/.............................../lib/python3.10/site-packages/grid2viz/src/kpi/EpisodeAnalytics.py:135: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  load_data.loc[:, "value"] = load_data.loc[:, "value"].astype(float)
```

```
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by marota** [comment]
Great, I updated the ReadMe a bit so that it is less confusing what is expected in agents_path
