### ISSUE TITLE
Pandas error after installation

### ISSUE THREAD

**Issue by pmacedo-19** [rte-france/grid2viz#108]
I've been trying to use grid2viz for some testing but i never really was able to make it run.

Firstly after install i always have a problem with the **werkzeug** package. It is easily solved with an installation from source.

>ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/home/wardian/venv_grid2viz/lib/python3.10/site-packages/werkzeug/debug/tbtools.py)

After that i run into the real issue. When i try to run the command it crashes with an error on **pandas/core/frane.py**.

>grid2viz --port 8000                                  
Using default agents logs at /home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/data/agents
Using default environment at /home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/data/rte_case14_realistic
The config file used is located at: /home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/config.ini
Agents data used is located at: /home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/data/agents
Traceback (most recent call last):
  File "/home/wardian/venv_grid2viz/bin/grid2viz", line 8, in <module>
    sys.exit(main())
  File "/home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/main.py", line 140, in main
    from grid2viz.app import app_run, define_layout_and_callbacks
  File "/home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/app.py", line 29, in <module>
    from grid2viz.main_callbacks import register_callbacks_main
  File "/home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/main_callbacks.py", line 18, in <module>
    from grid2viz.src.overview import overview_lyt as overview
  File "/home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/src/overview/overview_lyt.py", line 22, in <module>
    from grid2viz.src.manager import (
  File "/home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/src/manager.py", line 643, in <module>
    meta_json, best_agents, survival_df, attention_df = check_all_tree_and_get_meta_and_best(
  File "/home/wardian/venv_grid2viz/lib/python3.10/site-packages/grid2viz/src/manager.py", line 560, in check_all_tree_and_get_meta_and_best
    survival_df = pd.DataFrame(columns=agents, index=scenarios)
  File "/home/wardian/venv_grid2viz/lib/python3.10/site-packages/pandas-2.0.0.dev0+916.ge0b93cce71-py3.10-linux-x86_64.egg/pandas/core/frame.py", line 654, in __init__
    raise ValueError("index cannot be a set")
ValueError: index cannot be a set

Hope you can help

**Comment by BDonnot** [comment]
Hi 😊

To write it somewhere : pandas 1.4.4 seems to be working.

Thanks for letting us know
