### ISSUE TITLE
Some issues in running Grid2viz

### ISSUE THREAD

**Issue by djmax008** [rte-france/grid2viz#6]
Dear Artelys,

A great visualization tool for Grid2op.
It works perfectly if my agent takes no action or splitting nodes. 
The problem is if the agent takes the "reconnect power line" action the Grid2viz can not be compiled.
Here is an example. In chronic 0 time step 527, the agent takes the following actions to reconnect the broken line 5.
action_transf_dict = self.agent_action_space.reconnect_powerline(line_id=i,bus_or=1,bus_ex=1)
'''
This action will:
	 - NOT change anything to the injections
	 - NOT perform any redispatching action
	 - force reconnection of 1 powerlines ([5])
	 - NOT switch any line status
	 - NOT switch anything in the topology
	 - Set the bus of the following element:
	 	 - assign bus 1 to line (origin) 5 [on substation 11]
	 	 - assign bus 1 to line (extremity) 5 [on substation 12]
'''

After this action, line 5 is broken again medievally due to the thermal limit. And the environment modified action (env.env_modification) is 
'''
This action will:
- set load_p to [ 24.2 103.3  15.9  49.4   8.   12.6  33.2  10.2   4.2   6.8  14.5]
- set prod_p to [83.7 81.6 39.1  0.  82.6]
- set load_q to [16.8 72.7 11.3 34.2  5.7  8.7 23.3  7.2  2.9  4.9 10. ]
- set prod_v to [142.1 142.1   0.2  12.  142.1]
- NOT perform any redispatching action
- NOT force any line status
- NOT switch any line status
- NOT switch anything in the topology
- NOT force any particular bus configuration
'''

Finally, it will result in the Grid2viz stuck at time step 527 timestep during compiling. And the error is
'''
 99%|███████████████████████████████████████▋| 527/531 [00:01<00:00, 394.56it/s]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/dash/dash.py", line 1459, in dispatch
    response.set_data(self.callback_map[output]["callback"](*args))
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/dash/dash.py", line 1339, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/home/jiajun/Desktop/grid2viz-master/grid2viz/src/episodes/episodes_clbk.py", line 32, in load_scenario_cards
    best_agent_episode = make_episode(best_agents[scenario]['agent'], scenario)
  File "/home/jiajun/Desktop/grid2viz-master/grid2viz/src/manager.py", line 49, in make_episode
    episode = compute_episode(episode_name, agent)
  File "/home/jiajun/Desktop/grid2viz-master/grid2viz/src/manager.py", line 90, in compute_episode
    ), episode_name, agent)
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/grid2kpi/episode/EpisodeAnalytics.py", line 27, in __init__
    self.load, self.production, self.rho, self.action_data_table, self.computed_reward, self.flow_and_voltage_line = self._make_df_from_data()
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/grid2kpi/episode/EpisodeAnalytics.py", line 192, in _make_df_from_data
    production["timestamp"] = np.repeat(self.timestamps, self.n_prods)
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2938, in __setitem__
    self._set_item(key, value)
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 3000, in _set_item
    value = self._sanitize_column(key, value)
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 3636, in _sanitize_column
    value = sanitize_index(value, self.index, copy=False)
  File "/home/jiajun/anaconda3/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 611, in sanitize_index
    raise ValueError("Length of values does not match length of index")
ValueError: Length of values does not match length of index
'''

Could you please help us to fix this problem?

Thanks,
Jiajun

**Comment by vinault** [comment]
Dear Jiajun, 
could you please attach the scenario files for this agent so that I can try and reproduce the error? 
Best, 
Vincent

**Comment by djmax008** [comment]
Dear Vincent,

No problem, please try the attachments.
Each chronic has over 8,000 time steps. If you always take no action, certain lines will be broken.
And if you connect broken line after 10 steps cooldown time,  the line may be reconnected.
The Grid2viz always stucks at this time step of reconnecting the power line.
[data.zip](https://github.com/mjothy/grid2viz/files/4372363/data.zip)

Jiajun

**Comment by djmax008** [comment]
Dear Vincent,

have you found the problem?

Jiajun

**Comment by vinault** [comment]
Dear Jiajun,

I actually wasn't able to look into it until now. If i'm not mistaken, the
data you provided only consists of the chronics data. I'd need the
grid2viz input files also to be able to reproduce your problem.
Can you provide them as well ?

Cheers,
Vincent

**Comment by djmax008** [comment]
Dear Vincent,

No problem. please see the attachment.

Best,
Jiajun
[agent1.zip](https://github.com/mjothy/grid2viz/files/4397846/agent1.zip)

**Comment by marota** [comment]
Vincent,

If you need to know at which timestep you have a gameover, you get the info in episode_meta.json:

- "nb_timestep_played": 1824

**Comment by vinault** [comment]
Hi @djmax008, 

Thank you for your patience. Did you by any chance ran your agent1 (previously linked) on a recent version of Grid2Op. I fixed the bug but the agent1 does not run on Grid2Op 0.9.4. If you had a version compatible with 0.9.4 it would be super useful. Thanks
